export const testLang = {
  uz: {
    t1: 'Course Yakuniy testlar',
    t2: 'Add Test',
    t3: "Test o'chiriladi",
    t4: 'Ishonchingiz komilmi ?',
    t5: 'Ha',
    t6: 'Yoq',
    t7: 'Test Sarlavhasi',
    t8: 'Title',
    t9: 'Description',
    t10: 'Savol',
    t11: 'Send',
  },
  kr: {
    t1: '코스 최종 테스트',
    t2: '테스트 추가',
    t3: '오치릴라디 테스트',
    t4: '확실해?',
    t5: '하',
    t6: '노크는',
    t7: '테스트 제목',
    t8: '제목',
    t9: '설명',
    t10: '질문',
    t11: '보내기',
  },
};
