export const courseLang = {
  uz: {
    t1: 'Kurslar',
    t2: 'Sarlavha',
    t3: 'Narxi',
    t4: 'Ketma-Ketlik',
    t5: 'Izoh',
    t6: 'Image',
    t7: 'Video + Workbook',
    t8: "so'm",
    t9: "O'zgartirish",
    t10: "O'chirish",
    t11: 'Sarlavha',
    t12: 'Narxi',
    t13: 'Ketma-Ketlik',
    t14: 'Izoh',
    t15: 'Image',
  },
  kr: {
    t1: '코스',
    t2: '제목',
    t3: '가격',
    t4: '순서',
    t5: '참고',
    t6: '이미지',
    t7: '비디오+통합 문서',
    t8: '그래서',
    t9: '오즈가티리쉬',
    t10: '오치리시',
    t11: '제목',
    t12: '가격',
    t13: '순서',
    t14: '참고',
    t15: '이미지',
  },
};
