export const usersLang = {
  uz: {
    t1: 'Users',
    t2: 'E-Mail search',
    t3: 'Phone Number search',
    t4: 'Active',
    t5: 'Blocked',
    t6: "Ro'yxat uzunligi",
    t7: 'Foydalanuvchini Block qilish',
    t8: 'Ishonchingiz komilmi?',
    t9: "Foydanaluvchini qora ro'yxatga tushgach",
    t10: 'ortga qaytarish imkoni yoq',
    t11: 'Ha',
    t12: 'Yoq',
    t13: 'status',
    t14: 'Jami Kurs',
    t15: 'Jami foyda',
    ta: 'ta',
    som: "so'm",
    t16: "Foydalanuvchini habari yo'q",
    t17: 'Ismi',
    t18: 'Familiya',
    t19: 'Rasmi',
  },
  kr: {
    t1: '사용자',
    t2: '이메일 검색',
    t3: '전화 번호 검색',
    t4: '활성',
    t5: '차단됨',
    t6: '목록 길이',
    t7: '사용자 차단',
    t8: '확실해?',
    t9: '수혜자를 블랙리스트에 올린 후',
    t10: '돌아 오는 길',
    t11: '예',
    t12: '아니',
    t13: '상태',
    t14: '전체 코스',
    t15: '총 이익',
    ta: '타',
    som: '소무',
    t16: '사용자 인식 없음',
    t17: '이름',
    t18: '성명',
    t19: '공식',
  },
};
