export const videoLang = {
  uz: {
    t1: 'Video darslik yuklash',
    t2: 'Add Video',
    t3: 'Dars',
    t4: "Videoni o'chirmoqchimisiz",
    t5: 'Ishonchingiz komilmi?',
    t6: 'Ha',
    t7: 'Yoq',
    t8: 'Video Sarlavhasi',
    t9: 'Video Ketma-ketligi',
    t10: "Hozirgi o'rni",
    t11: 'dars',
    t12: 'Video nechinchi dars?',
    t13: 'Video yuklash',
    t14: 'Video kursni yuklang',
    t15: "Videoni o'chirish",
    t16: 'Video comment',
    t17: 'Ortga Qaytish',
    t18: "Videoni o'zgartirish",
    t19: 'Videoni joylash',
  },
  kr: {
    t1: '비디오 다슬릭 유클라시',
    t2: '비디오 추가',
    t3: '다르스',
    t4: '당신은 비디오를 삭제 하시겠습니까',
    t5: '확실해?',
    t6: '하',
    t7: '노크는',
    t8: '비디오 제목',
    t9: '비디오 시퀀스',
    t10: '현재 위치',
    t11: '수업',
    t12: '비디오에 얼마나 많은 수업이 있습니까?',
    t13: '비디오 업로드',
    t14: '비디오 코스 업로드',
    t15: '비디오 삭제',
    t16: '비디오 코멘트',
    t17: '오르테가 카이티시',
    t18: '비디오 변환',
    t19: '비디오 위치',
  },
};
