export const bookLang = {
  uz: {
    t1: 'Workbook yuklash',
    t2: 'Add Workbook',
    t3: 'Dars',
    t4: "Workbookni o'chirmoqchimisiz",
    t5: 'Ishonchingiz komilmi?',
    t6: 'Ha',
    t7: "Yo'q",
    t8: 'Workbook Sarlavhasi',
    t9: 'Workbook yuklash',
    t10: "PDF rasm ko'rish",
    t11: 'Workbook kursni yuklang',
    t12: "Workbookni o'chirish",
    t13: 'Ortga Qaytish',
    t14: 'Workbookni joylash',
  },
  kr: {
    t1: '워크북 유클래시',
    t2: '통합 문서 추가',
    t3: '다르스',
    t4: '워크북 오치르모크치미시즈',
    t5: '확실해?',
    t6: '하',
    t7: '아니',
    t8: '워크북 사르라바시',
    t9: '워크북 유클래시',
    t10: '이미지 보기',
    t11: '워크북 쿠르스니 유클랑',
    t12: '워크부키 오치리시',
    t13: '오르트가 카이티시',
    t14: '워크북니 조일래시',
  },
};
