export const courseLang = {
  uz: {
    t1: 'Yangiliklar',
    t2: 'Add Video',
    t3: "News o'chiriladi",
    t4: 'Ishonchingiz komilmi ?',
    t5: 'Ha',
    t6: "Yo'q",
    t7: 'News Sarlavhasi',
    t8: 'News Rasmi (Ixtiyoriy)',
    t9: 'News uchun Rasm yuklang',
    t10: 'News comment',
    t11: 'Ortga Qaytish',
    t12: "Newsni o'zgartirish",
    t13: 'Newsni joylash',
  },
  kr: {
    t1: '양길리클라르',
    t2: '비디오 추가',
    t3: '뉴스 오치릴라디',
    t4: '확실해?',
    t5: '하',
    t6: '아니',
    t7: '뉴스 사르라바시',
    t8: '뉴스 라스미(익스티요리)',
    t9: '뉴스 우춘 라스 유클랑',
    t10: '뉴스 코멘트',
    t11: '오르테가 카이티시',
    t12: '뉴스 니 오즈가티리쉬',
    t13: '뉴스니 조일래시',
  },
};
